"use client";
import { useId, useRef, useState } from "react";
import Link from "next/link";
import type { Outline } from "@/lib/course";
import { levelPercent, levelUnlocked, useStore } from "@/lib/progress";
import LevelBadge from "@/components/art/LevelBadge";
import { Lock, Check } from "@/components/ui/Icons";
export type RoadmapLevel = Outline & { title: string; capstone: string };
type Selection = { level: RoadmapLevel; chapter: Outline["chapters"][number]; lesson: Outline["chapters"][number]["lessons"][number] };
export default function LearningRoadmap({ levels }: { levels: RoadmapLevel[] }) {
 const {progress,ready}=useStore();const [query,setQuery]=useState("");const [selected,setSelected]=useState<Selection|null>(null);const dialog=useRef<HTMLDialogElement>(null);const id=useId();
 const open=(choice:Selection)=>{setSelected(choice);dialog.current?.showModal();};
 const available=(slug:string)=>slug==="01" || (ready && levelUnlocked(slug,progress.done));
 const matches=(title:string)=>title.toLowerCase().includes(query.trim().toLowerCase());
 const count=levels.flatMap(l=>l.chapters.flatMap(c=>c.lessons)).filter(l=>matches(l.title)).length;
 return <div className="learning-roadmap"><div className="roadmap-tools"><label htmlFor={`${id}-search`}>Find a lesson<input id={`${id}-search`} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try research, metrics, AI…"/></label><p><span className="roadmap-dot"/> Open <span className="roadmap-dot locked"/> Preview <Check className="h-3 w-3"/> Complete</p><span className="roadmap-count" role="status">{count} lessons</span></div>
 <nav className="roadmap-jumps" aria-label="Jump to a level">{levels.map(l=><a key={l.slug} href={`#roadmap-${l.slug}`}>{l.n} <span>{l.rank}</span></a>)}</nav>
 <div className="roadmap-path">{levels.map(level=>{const unlocked=available(level.slug);const chapters=level.chapters.map(c=>({...c,lessons:c.lessons.filter(l=>matches(l.title))})).filter(c=>c.lessons.length);if(!chapters.length)return null;return <section key={level.slug} id={`roadmap-${level.slug}`} className={`roadmap-level ${unlocked?'is-open':'is-locked'}`}><header className="roadmap-level-head"><div className="roadmap-badge"><LevelBadge n={level.n}/></div><div><span className="eyebrow">Level {level.n} · {level.rank}</span><h2>{level.title}</h2><p>{unlocked ? `${ready?levelPercent(level.slug,progress.done):0}% complete · Ready to learn` : `Preview the path · Complete earlier levels to begin`}</p></div><Link href={`/levels/${level.slug}`} className="roadmap-overview">Level overview ↗</Link></header><div className="roadmap-branches">{chapters.map(chapter=><section className="roadmap-chapter" key={chapter.slug}><h3><span>{level.n}.{chapter.n}</span>{chapter.title}</h3><ol>{chapter.lessons.map(lesson=>{const done=progress.done.includes(`${level.slug}/${lesson.slug}`);return <li key={lesson.slug}><button type="button" className={`roadmap-cell ${done?'is-done':''}`} onClick={()=>open({level,chapter,lesson})}><span>{lesson.title}</span>{done?<Check className="h-3.5 w-3.5"/>:!unlocked?<Lock className="h-3.5 w-3.5"/>:<span aria-hidden="true">↗</span>}<span className="sr-only">{done?'Completed':unlocked?'Open lesson preview':'Locked lesson preview'}</span></button></li>})}</ol></section>)}</div><div className="roadmap-capstone"><span aria-hidden="true">✦</span><p><span className="eyebrow">The level capstone</span>{level.capstone}</p><span>Build → submit → review</span></div></section>})}</div>
 {count===0&&<div className="roadmap-empty"><h2>No lesson names match that search.</h2><button className="btn btn-outline" onClick={()=>setQuery("")}>Show every lesson</button></div>}
 <dialog ref={dialog} className="lesson-preview" aria-labelledby={`${id}-title`} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button className="preview-close" type="button" aria-label="Close lesson preview" onClick={()=>dialog.current?.close()}>×</button>{selected&&<><span className="eyebrow">Level {selected.level.n} · {selected.chapter.title}</span><h2 id={`${id}-title`}>{selected.lesson.title}</h2><p>{selected.lesson.kind} · About {selected.lesson.minutes} minutes</p><div className="preview-status">{available(selected.level.slug)?<><Check className="h-5 w-5"/><p>This lesson is open. Bring your project and work through the build.</p></>:<><Lock className="h-5 w-5"/><p>Finish all earlier levels before starting Level {selected.level.n}. You can preview lesson names now; the learning content opens when you are ready.</p></>}</div><div className="page-actions">{available(selected.level.slug)?<Link className="btn btn-primary" href={`/levels/${selected.level.slug}/${selected.lesson.slug}`} onClick={()=>dialog.current?.close()}>Open lesson ↗</Link>:<Link className="btn btn-primary" href={`/levels/${levels.find(l=>!levelPercent(l.slug,progress.done)||levelPercent(l.slug,progress.done)<100)?.slug ?? '01'}`} onClick={()=>dialog.current?.close()}>Continue earlier work ↗</Link>}<button type="button" className="btn btn-outline" onClick={()=>dialog.current?.close()}>Keep exploring</button></div></>}</dialog>
 <p className="roadmap-footnote">Progress is saved on this browser. A completed level opens the next; badges are awarded separately after capstone review.</p>
 </div>;
}
