export type CaseCard = { brand: string; title: string; category: string; summary: string; href: string; format: "Visual case study" | "Source reading"; art: "streak" | "research" | "form" | "collaboration" };
export const caseLibrary: CaseCard[] = [
 {brand:"Duolingo",title:"One lesson. A better reason to return.",category:"Retention",summary:"Explore the product decision behind a more forgiving streak, then test the trade-offs yourself.",href:"/case-studies/duolingo-streak",format:"Visual case study",art:"streak"},
 {brand:"Superhuman",title:"Find the people who need you most.",category:"Discovery",summary:"A founder's account of using a product-market-fit survey to sharpen a target audience and guide product work.",href:"https://review.firstround.com/how-superhuman-built-an-engine-to-find-product-market-fit/",format:"Source reading",art:"research"},
 {brand:"GOV.UK",title:"Give each question room to breathe.",category:"Onboarding",summary:"The official question-page pattern explains how to focus a form on the information a user needs to provide.",href:"https://design-system.service.gov.uk/patterns/question-pages/",format:"Source reading",art:"form"},
 {brand:"Figma",title:"When everyone edits at once.",category:"Systems",summary:"Figma's engineering account of multiplayer editing connects a collaborative experience with the system that supports it.",href:"https://www.figma.com/blog/how-figmas-multiplayer-technology-works/",format:"Source reading",art:"collaboration"},
];
export const streakSources = {
 rule:{label:"Duolingo: Improving the streak",url:"https://blog.duolingo.com/improving-the-streak/"},
 design:{label:"Duolingo: Animating the streak",url:"https://blog.duolingo.com/streak-milestone-design-animation/"},
 habit:{label:"Duolingo: How the streak builds a habit",url:"https://blog.duolingo.com/how-duolingo-streak-builds-habit/"},
};
export const streakChapters = [
 {id:"tension",label:"The tension",title:"Showing up did not always count.",source:"rule",fact:"Duolingo describes an earlier rule that linked streak extension to a learner's daily goal. Some learners returned on consecutive days but did not earn a streak because they had not reached that goal.",analysis:["Start with a fictional learner, Sam. Sam has five minutes tonight and completes one lesson. A product can recognise that effort, encourage more practice, or imply that the day did not count. Those choices communicate different definitions of success.","Before suggesting a reminder, inspect the rule behind the feedback. Your project question is whether the product recognises a useful action at the moment the user performs it. Write the action, eligibility conditions, and confirmation state in plain language. A screen redesign cannot repair an incoherent rule by itself."],question:"For your project: what useful action might go unrecognised today?"},
 {id:"rule",label:"The rule",title:"Separate consistency from intensity.",source:"rule",fact:"The team tested extending a streak after one lesson, while showing progress toward the daily goal separately. This changed the qualification rule rather than simply adding a more persuasive message.",analysis:["Use the simulator to compare the rules. The four-lesson target is a teaching assumption, not a reconstruction of a particular learner's account. Notice that the goal can remain ambitious while the minimum recognised action becomes smaller.","For your own product, define a minimum action that still creates value. Opening a dashboard may be too weak; completing a useful task may be enough. Check for accidental incentives: if the easiest qualifying action becomes all people do, will the product still help them? Put that concern next to your main outcome before launching."],question:"Write two separate definitions: a meaningful return and a stretch goal."},
 {id:"feedback",label:"The feedback",title:"Make the outcome legible, then celebrate.",source:"design",fact:"Duolingo's design account describes revisiting the streak metaphor, developing milestone animations, and adding shareable achievement cards. The work included exploration and animation timing, not just a new icon.",analysis:["A useful sequence is action, confirmation, then celebration. If the learner has to watch an animation to discover whether their work saved, decoration has taken priority over clarity. The essential outcome should remain visible when motion is paused or disabled.","Try the replay below. Our original illustration is a teaching reconstruction, not Duolingo's interface. In your own prototype, test whether someone can explain what happened after a brief glance. Then ask whether the motion feels rewarding, distracting, or obligatory. Those observations can help you refine timing without treating delight as a universal preference."],question:"What must remain understandable when every animation is turned off?"},
 {id:"recovery",label:"The recovery",title:"Design for an imperfect week.",source:"habit",fact:"Duolingo describes Streak Freezes as flexibility for missed practice days. Its account also reports that allowing two equipped freezes increased daily active learners by 0.38% relative in that experiment.",analysis:["In the illustrative week below, a protected missed day preserves the counter but does not represent a completed lesson. Keep those concepts separate. The interface should not imply that protecting a record is the same as acquiring knowledge.","For your product, map the return after a lapse as carefully as the first success. What does the person still have? What must they do next? Can they decline a reminder or return without shame? An ethical recovery design gives an understandable route back and preserves choice. It should not manufacture urgency or pretend a setback erased genuine progress."],question:"What can your product preserve after a missed day without misrepresenting achievement?"},
 {id:"evidence",label:"The evidence",title:"Read the lift with its trade-off.",source:"rule",fact:"Duolingo reported a 3.3% relative increase in Day 14 retention and a 1% relative increase in daily active learners in the rule-separation experiment. It also reported fewer learners reaching their daily goals. These are historical company-reported results, not a forecast for another product.",analysis:["Relative change needs a baseline. The calculator uses a hypothetical baseline only to teach the arithmetic. It does not recover Duolingo's undisclosed control rate. A 3.3% relative increase is different from adding 3.3 percentage points.","Before deciding on your own experiment, define eligibility, random assignment, a meaningful return event, and a review window. Track a quality guardrail as well as activity. Predefine how much deterioration would trigger investigation. Public results rarely include every detail you would need to reproduce a study, so keep missing sample sizes, uncertainty estimates, and segment effects visible in your notes."],question:"Choose a main metric and a quality guardrail. How could they disagree?"},
 {id:"decision",label:"Your decision",title:"What would you ship first?",source:null,fact:"PMcademy practice decision. The options below are hypothetical and are not a claim about Duolingo's roadmap.",analysis:["Imagine your learning product has a problem: returning learners say that a small but useful session feels like failure. You have time for one focused change. Choose an option, read the trade-off, and explain what evidence could change your choice.","The purpose is not to memorise a winning feature. It is to connect a user problem to a mechanism, a test, and a boundary. A higher activity number alone cannot tell you whether the product is doing a better job for learners. Keep the decision small enough to inspect and reversible enough to learn from."],question:"What would make your preferred option the wrong next step?"},
 {id:"apply",label:"Make it yours",title:"Leave with a small experiment brief.",source:null,fact:"Your build: one page that turns the case into a decision for your own product.",analysis:["Describe the user situation in two sentences. Name the useful action that should count, the current rule, and the proposed rule. Sketch the confirmation and recovery states. Include an explicit way to decline reminders or leave the flow when that is relevant.","Choose a main outcome, a guardrail, and the evidence you need before shipping. Use AI to challenge the weakest assumption, not to invent a result. Keep source facts, your interpretation, and your proposed experiment in separate sections. Finish with a reason to stop or revise the idea. That turns a compelling story into a piece of product work you can defend."],question:"Save the brief with your project. What is the cheapest check you can run next?"},
] as const;
