import type { PolicySection } from "@/components/pages/PolicyPage";
export const privacySections: PolicySection[] = [
 {id:"who",title:"Who handles your information",paragraphs:["PMcademy is run by the team at OpenBootcamp, registered as M3V Technologies Private Limited (CIN: U62099PN2023PTC220005), Pune, Maharashtra, India. This policy explains information handled through our website, learning activities, support, and community services.","For privacy questions, requests, or concerns, contact hello@pmcademy.com. External websites and services have their own privacy policies."]},
 {id:"information",title:"Information you provide",paragraphs:["When you email us, enrol in a paid service, submit work for review, or participate in a community, we may receive your name, contact details, purchase or enrolment information, messages, and the work you choose to share. We use the information relevant to the service you request.","Do not include passwords, payment-card details, identity documents, confidential employer information, or another person's private data in project work or support messages. Where a payment service is used, payment details are handled by that provider; send us an order reference rather than card details."]},
 {id:"browser",title:"Progress, preferences, and local storage",paragraphs:["This website currently saves learning progress, checklist answers, case-study briefs, project article links, selected learning preferences, and theme settings in your browser. These local records do not automatically synchronise across devices or reach a capstone reviewer. Some account-interface details are also stored locally in this version.","You can remove local records through your browser's site-data controls. Doing so may reset progress, preferences, and saved links. If you also shared information with us through email or another service, clearing this website's browser data does not erase those separate records."]},
 {id:"presence",title:"The online learner indicator",paragraphs:["When the live activity feature is available, a temporary anonymous cookie groups your browser tabs into one visit. Visible pages send periodic heartbeats so the website can show an approximate number of active browsers, including visitors who have not signed in.","The presence store contains a random browser identifier and its last activity timestamp, not your name, email, account, or lesson URL. Visits stop counting after 90 seconds without a heartbeat. The presence cookie lasts up to one day, and the shared activity set expires after 180 seconds without updates. This number measures browser activity, not confirmed study time or unique people."]},
 {id:"purposes",title:"How information is used",paragraphs:["We use information to provide learning and paid services, respond to messages, review submitted work, maintain purchase records, protect the platform, and address conduct concerns. We do not sell your personal information.","We may use hosting, email, payment, and community providers to deliver these functions. Providers can process technical information such as network addresses, browser details, and request logs. Fonts loaded from an external font service also create requests to that service. We share information when necessary to deliver the requested service, meet legal obligations, or protect people and the platform."]},
 {id:"sharing",title:"Projects, community posts, and AI tools",paragraphs:["Information you post in a community or publish on Medium, Substack, Reddit, or another platform may be visible to that audience. Consider the audience before sharing. You retain responsibility for obtaining permission to publish third-party material.","Course prompts are provided for you to use in your chosen AI tool. Copying material into that tool is your action and is governed by its terms and privacy settings. The website does not automatically send your lesson answers to an AI provider. Remove private details before using external tools."]},
 {id:"retention",title:"Retention and security",paragraphs:["Local learning records remain until you or your browser remove them. Support, enrolment, review, and moderation records are retained for as long as needed for their purpose, applicable record-keeping obligations, or a relevant dispute. Where information is no longer needed, we take steps to delete or de-identify it.","We use reasonable safeguards appropriate to the information and service. No storage or transmission method is completely secure. Providers may process information outside your location, subject to applicable requirements and the arrangements used to provide the service."]},
 {id:"choices",title:"Your choices and requests",paragraphs:["Contact hello@pmcademy.com to request access, correction, or deletion of information held by us, withdraw a consent where processing depends on it, or raise a privacy concern. We may need proportionate information to verify the request. Some records may need to be retained where the law requires it.","You may stop using the website or adjust browser cookie and storage settings. Some features will then be unavailable or forget your preferences. Privacy choices do not themselves cancel an enrolment or create a refund entitlement.","If you are under 18, involve your parent or lawful guardian before providing personal information or enrolling in a paid service. Contact us if you believe a child has shared information without appropriate authorisation."]},
 {id:"updates",title:"Changes to this policy",paragraphs:["We will update this page when our practices change and revise the date above. Material changes affecting information already collected will be handled with any notice or consent required by applicable law. Contact us if anything in this policy is unclear."]},
];
export const termsSections: PolicySection[] = [
 {id:"agreement",title:"Using PMcademy",paragraphs:["These terms govern use of PMcademy's website, learning materials, paid services, and community. PMcademy is run by OpenBootcamp through M3V Technologies Private Limited, CIN U62099PN2023PTC220005, Pune, Maharashtra, India. Our primary contact is hello@pmcademy.com.","By using the platform or enrolling, you agree to these terms and the applicable enrolment details. If you do not agree, do not enrol or use the service. Paid enrolment must be made by someone legally able to enter the agreement, or with appropriate parent or guardian involvement."]},
 {id:"learning",title:"Learning access and badges",paragraphs:["The six-level curriculum is available free of charge. Later levels open as earlier levels are completed. Paid community access and capstone review are separate from free course access; the offer shown at enrolment describes the purchased service.","Completing a lesson or purchasing access does not automatically earn a badge. Badges depend on the stated capstone review requirements. Educational content, feedback, and community introductions do not guarantee employment, income, admission, promotion, or a particular business result.","Keep copies of important work and submission links. Browser-local progress can be lost if site data is cleared and is not a substitute for submitting work for review."]},
 {id:"enrolment",title:"Fees and enrolment",paragraphs:["Review the price, inclusions, eligibility, technical requirements, and policies before enrolling. You are responsible for providing accurate enrolment information and using a payment method you are authorised to use.","Once enrolled, we do not offer refunds or cancellations for a change of mind, non-participation, scheduling conflicts, or failure to complete the course. The Refunds & Cancellations policy explains this rule and the limited exception for rights or remedies that applicable law requires. A one-time purchase is not a recurring subscription unless an offer expressly says otherwise."]},
 {id:"conduct",title:"A respectful, relevant learning space",paragraphs:["Treat colleagues, learners, mentors, and staff with respect. Critique ideas and work constructively. PMcademy requires ethical participation across its platform and associated community spaces."],items:["Do not harass, threaten, bully, discriminate against, or abuse anyone. Personal attacks and hateful or sexually inappropriate content are prohibited.","Keep posts relevant to the learning topic and the channel. Do not repeatedly post unrelated topics, spam, unsolicited promotions, scams, or disruptive messages.","Do not impersonate others, share access improperly, interfere with the platform, or attempt unauthorised access to accounts or systems.","Do not plagiarise, fabricate research or results, misrepresent AI-generated work as evidence you collected, or submit another person's work as your own.","Respect intellectual property and confidentiality. Do not share private participant, employer, customer, or community information without permission.","Follow reasonable moderator instructions and the additional rules of the community space you use."]},
 {id:"moderation",title:"Moderation, suspension, and removal",paragraphs:["PMcademy reserves the right to remove content, restrict participation, suspend access, or remove a student who breaches these terms or ethical and community guidelines. Depending on severity, repeated violations, or risk to others, action may be taken without a prior warning.","Where appropriate, we may explain the action or request a correction. You can ask for a review by emailing hello@pmcademy.com with the relevant details. Removal for misconduct does not create a contractual refund entitlement, subject to any remedy required by applicable law. We may retain necessary records to handle the concern and protect participants."]},
 {id:"work",title:"Your work and our materials",paragraphs:["You retain ownership of original work you create. By submitting or posting it, you permit us to host, display to the intended audience, and review it as necessary to provide the service. This does not give us unrestricted permission to use your name or project in marketing; any separate permission will be requested where needed.","PMcademy's original course materials and artwork are protected by applicable intellectual-property rights. You may use them for your personal learning and follow the stated terms of downloadable resources. Do not redistribute the course as your own paid product or remove attribution. Third-party names, images, and materials remain the property of their owners."]},
 {id:"tools",title:"External tools and case studies",paragraphs:["External products, articles, and AI tools are governed by their own terms. You choose whether to use them and are responsible for costs or information you share with them. Public case studies are independent educational commentary, not an endorsement or affiliation with the featured company.","AI assistance does not replace checking facts, respecting privacy, or making your own judgments. Examples marked fictional or illustrative are teaching material, not company research findings."]},
 {id:"availability",title:"Availability and responsibility",paragraphs:["We may maintain, improve, or update content and services. Temporary interruptions can occur. We will handle material changes to purchased services in accordance with the enrolment terms and applicable law.","Use educational material with judgment and obtain qualified advice where a decision requires it. To the extent permitted by law, we are not responsible for indirect losses arising from your application of course material. Nothing in these terms excludes liability, consumer protections, or other rights that cannot lawfully be excluded."]},
 {id:"law",title:"Questions, disputes, and changes",paragraphs:["Start by contacting hello@pmcademy.com so we can understand and address the concern. These terms are governed by the laws of India. Courts with jurisdiction in Pune, Maharashtra apply, subject to any mandatory rights to approach a competent consumer forum or other authority.","We may revise these terms and update the date on this page. Changes will not remove rights already acquired under applicable law. Material changes will be communicated where required. Our Privacy and Refunds & Cancellations policies should be read alongside these terms."]},
];
export const refundSections: PolicySection[] = [
 {id:"policy",title:"No refunds or cancellations after enrolment",paragraphs:["Once enrolled in a paid PMcademy service, your enrolment is final. We do not offer refunds or cancellations for change of mind, lack of time, non-attendance, non-use, changes in personal circumstances, dissatisfaction with your own progress, or failure to complete the course or earn a badge.","Please review the curriculum, service inclusions, price, requirements, and these policies before enrolling. You can explore the free lessons and contact hello@pmcademy.com with questions before making a payment."]},
 {id:"access",title:"Stopping participation",paragraphs:["You can choose to stop studying or participating at any time. Stopping participation, asking to close an account, clearing browser data, or choosing not to submit a capstone does not cancel an enrolled purchase or create a refund entitlement.","The current badge and community offer is a one-time payment, not a recurring subscription. There is no recurring renewal to cancel under that offer. Free course access does not involve a course fee to refund."]},
 {id:"removal",title:"Removal for misconduct",paragraphs:["Students who breach the Terms or community guidelines may be suspended or removed from PMcademy. This includes abuse, harassment, unethical conduct, repeated unrelated posting, spam, and disrespectful or disruptive behaviour. Removal for a breach does not create a contractual right to a refund.","You may request a review of a moderation decision at hello@pmcademy.com. Include the relevant account or enrolment reference and a clear description of the concern."]},
 {id:"rights",title:"Payment errors and rights required by law",paragraphs:["This policy does not exclude refunds, corrections, or other remedies that applicable law requires. A duplicate or erroneous payment, an unauthorised transaction, or a failure to supply a purchased service should be reported so the facts and applicable obligations can be reviewed. These are not change-of-mind cancellations.","If a refund or correction is required, we will explain the next steps after reviewing the issue. Processing depends on the payment method and provider. We do not promise a processing timeline before the relevant transaction has been checked."]},
 {id:"contact",title:"How to raise a concern",paragraphs:["Email hello@pmcademy.com with the name and email used for enrolment, payment date, order or transaction reference, and a short explanation. Do not send full card details, passwords, or sensitive financial records.","PMcademy is run by the team at OpenBootcamp, registered as M3V Technologies Private Limited, CIN U62099PN2023PTC220005, Pune, Maharashtra, India."]},
];
