'use client';
import {useId,useState} from 'react';
import MotionFrame from '@/components/art/MotionFrame';
type Kind='sampling'|'recruitment'|'questions'|'coding'|'agreement'|'usability'|'sizing'|'pmf'|'cohorts'|'experiment';
const titles:Record<Kind,string>={sampling:'Whose experience is missing?',recruitment:'Find the leak in the funnel',questions:'Change the question, change the evidence',coding:'Keep the quote attached to its source',agreement:'Inspect the disagreement',usability:'Assistance changes the outcome',sizing:'Move the assumption',pmf:'A percentage needs a denominator',cohorts:'A blank is not a failure',experiment:'Let a guardrail change the decision'};
export default function ResearchLab({kind}:{kind:Kind}){const [value,setValue]=useState(kind==='sizing'?300:kind==='pmf'?20:50),[on,setOn]=useState(false),id=useId();let labels:string[]=[],values:number[]=[],output='',note='';let controls:React.ReactNode;const toggle=(label:string)=><button type="button" className="lab-toggle" aria-pressed={on} onClick={()=>setOn(v=>!v)}>{label}</button>;const range=(label:string,min:number,max:number)=><label className="research-range" htmlFor={id}>{label}: <strong>{value}</strong><input id={id} type="range" min={min} max={max} value={value} onChange={e=>setValue(Number(e.target.value))}/></label>;
if(kind==='sampling'){labels=['Successes','Abandoners','Alternatives'];values=on?[4,4,4]:[12,0,0];controls=toggle(on?'Show convenient sample':'Include missing experiences');output=on?'Three experiences represented; still not a representative survey.':'Twelve enthusiastic users. Two experiences absent.';note='Interview quotas create useful contrasts. They do not estimate the population share of each experience.';}
if(kind==='recruitment'){labels=['Replied','Eligible','Booked','Attended'];values=[20,12,8,Math.round(8*value/100)];controls=range('Attendance among bookings (%)',0,100);output=`${values[3]} attendees from 8 bookings and 100 invitations`;note='Only attendance changes in this fictional model. Keep the denominator attached to every rate.';}
if(kind==='questions'){labels=on?['Recent event','Actual steps','Workaround']:['Future intent','Suggested fix','Agreement'];controls=toggle(on?'Inspect leading version':'Rewrite neutrally');output=on?'“Walk me through the last report you prepared.”':'“Would an AI report save you time?”';note=on?'Follow the reported sequence. Drafting might not be the bottleneck.':'This proposes a solution and a benefit before the person describes a problem.';}
if(kind==='coding'){labels=['Source R07','Exact quote','Interpretation'];controls=toggle(on?'Show AI overstatement':'Restore source wording');output=on?'“I don’t always trust it for transfers.”':'“I never trust automatic categorisation.”';note=on?'Keep the condition “for transfers” visible and put interpretation in a separate field.':'The model strengthens the claim and removes its context. Reject the rewritten quotation.';}
if(kind==='agreement'){labels=['Both stale','Both missing','Disagree'];values=on?[10,8,2]:[9,7,4];controls=toggle(on?'Before clarified rules':'After clarified rules');output=`${values[0]+values[1]}/20 agreements`;note='Recoding the same sample is not independent validation. Keep an untouched set for that.';}
if(kind==='usability'){labels=['Unassisted','Assisted','Incomplete'];values=on?[2,2,1]:[4,0,1];controls=toggle(on?'Hide assistance detail':'Separate assistance');output=on?'2 unassisted, 2 assisted, 1 incomplete.':'4 completed. But did they need help?';note='Five fictional sessions help locate problems. They do not estimate a population success rate.';}
if(kind==='sizing'){labels=['5 min/event','7 min/event','10 min/event'];values=[value*10,value*14,value*20];controls=range('Affected people (assumed)',200,500);output=`${values[0].toLocaleString()}–${values[2].toLocaleString()} minutes / month`;note='People × 2 incidents each month × minutes per incident. This is possible workload, not proven savings or revenue.';}
if(kind==='pmf'){labels=['Strong support','Other'];values=[Math.round(value*.4),value-Math.round(value*.4)];controls=range('Survey responses',10,100);output=`${values[0]}/${value} = ${(values[0]/value*100).toFixed(1)}% strong support`;note='The approximate share is held fixed to expose the denominator. This is not a confidence calculation or a product-market fit certificate.';}
if(kind==='cohorts'){labels=['Jan · week 4','Feb · week 4','Mar · week 4'];values=[30,32,on?0:NaN];controls=toggle(on?'Restore unobserved cell':'Make the zero-fill mistake');output=on?'A false zero makes the youngest cohort look like a failure.':'March has not reached week four. Leave it unobserved.';note='The first two values are fictional percentages. The third cohort lacks the equivalent observation window.';}
if(kind==='experiment'){labels=['Report opens','Wrong exports'];values=on?[65,14]:[50,4];controls=toggle(on?'Inspect control':'Inspect proposed change');output=on?'Errors exceed the 8% guardrail. Investigate before rollout.':'Control: 50% open, 4% wrong-date exports.';note='Fictional decision exercise, not a statistical test. A guardrail must be able to change the decision.';}
const max=Math.max(1,...values.filter(Number.isFinite));return <section className="research-lab"><span className="eyebrow">Try the method · Illustrative data</span><h3>{titles[kind]}</h3><div className="research-controls">{controls}</div><MotionFrame label="research diagram"><svg viewBox="0 0 600 270" role="img" aria-label={output}><rect x="8" y="8" width="584" height="244" rx="20" fill="var(--surface-2)"/>{kind==='questions'||kind==='coding'?<g>{labels.map((label,i)=><g key={label} transform={`translate(${25+i*192} 70)`}><rect width="170" height="105" rx="15" fill={i===2?'var(--art-sage)':'var(--art-page)'} stroke="var(--art-outline)"/><text x="85" y="45" textAnchor="middle" fill="var(--art-label)" fontSize="15">{label}</text><path d="M24 65h122m-122 12h80" stroke="var(--art-outline)"/>{i<2&&<path className="research-trace" d="M172 52h19m-5-5 5 5-5 5" fill="none" stroke="var(--art-ochre)" strokeWidth="2"/>}</g>)}</g>:labels.map((label,i)=><g key={label} transform={`translate(25 ${28+i*52})`}><text y="18" fill="var(--ink)" fontSize="15">{label}</text><rect x="170" width="320" height="25" rx="5" fill="var(--surface)"/>{Number.isFinite(values[i])?<><rect className="research-bar" x="170" width={values[i]/max*290} height="25" rx="5" fill={i===labels.length-1?'var(--art-coral)':'var(--art-sage)'}/><text x="495" y="18" fill="var(--ink)" fontSize="15">{values[i]}</text></>:<text x="180" y="18" fill="var(--ink)" fontSize="14">Not yet observed</text>}</g>)}<path className="research-trace" d="M30 244h540" stroke="var(--art-ochre)" strokeWidth="2" strokeDasharray="4 10"/></svg></MotionFrame><output className="lab-result">{output}</output><p>{note}</p></section>;}
