import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { streakChapters, streakSources } from "@/lib/case-library";
import CaseArtwork from "@/components/case-studies/CaseArtwork";
import StreakLab from "@/components/case-studies/StreakLab";
import MotionFrame from "@/components/art/MotionFrame";
import ReadTracker from "@/components/workspace/ReadTracker";
export const metadata: Metadata = {title:"Duolingo: the decision behind a better streak",description:"An interactive product case study of streak rules, feedback, recovery, and the trade-offs behind retention. Based on Duolingo's published accounts."};
export default function StreakCasePage(){return <article className="shell page-wrap case-story"><Link className="case-back" href="/case-studies">← All case studies</Link><header className="case-story-hero"><div><span className="eyebrow">Duolingo · Retention · Visual case 01</span><h1>One lesson.<br/><em>A reason to return.</em></h1><p>A small rule can change what progress feels like. Explore the streak decision, inspect the evidence, and design a test for your own product.</p><div className="case-story-tags"><span>7 chapters</span><span>About 15 minutes</span><span>Free to explore</span></div><a className="btn btn-primary" href="#tension">Start the story ↓</a></div><MotionFrame label="cover illustration"><CaseArtwork/></MotionFrame></header><p className="case-disclosure">Independent PMcademy analysis of historical company publications. Illustrations and simulators are original teaching reconstructions, not current app screens. No affiliation with Duolingo.</p>
 <nav className="case-chapter-nav" aria-label="Case study chapters">{streakChapters.map((c,i)=><a key={c.id} href={`#${c.id}`}><span>0{i+1}</span>{c.label}</a>)}</nav>
 {streakChapters.map((c,i)=><section className="case-scene" id={c.id} key={c.id}><div className="case-scene-copy"><span className="eyebrow">Chapter 0{i+1} · {c.label}</span><h2>{c.title}</h2><div className="case-source-fact"><span className="eyebrow">{c.source?'Company account':'Your practice'}</span><p>{c.fact}</p>{c.source&&<a href={streakSources[c.source].url} target="_blank" rel="noreferrer">{streakSources[c.source].label} ↗</a>}</div><span className="case-analysis-label">PMcademy analysis & practice</span>{c.analysis.map(p=><p key={p}>{p}</p>)}<aside className="case-question"><span>Pause and think</span><p>{c.question}</p></aside>{i<streakChapters.length-1&&<a className="case-next" href={`#${streakChapters[i+1].id}`}>Next: {streakChapters[i+1].label} ↓</a>}</div><div className="case-scene-visual">{c.id==='tension'?<figure className="case-source-image"><Image src="/img/case-studies/duolingo-original-rule.png" alt="Historical Duolingo screen showing the daily goal linked to the streak." width={918} height={798} sizes="(max-width: 800px) 100vw, 45vw"/><figcaption>Historical source image, © Duolingo. From <a href={streakSources.rule.url} target="_blank" rel="noreferrer">Improving the streak</a>. Included to discuss the rule shown, not as a current UI reference.</figcaption></figure>:<><StreakLab kind={c.id}/>{c.id==='rule'&&<details className="case-historical"><summary>Inspect the published rule-change screen</summary><figure className="case-source-image"><Image src="/img/case-studies/duolingo-separated-rule.png" alt="Historical Duolingo screen showing streak extension separately from daily goal progress." width={920} height={820} sizes="(max-width: 800px) 100vw, 45vw"/><figcaption>Historical source image, © Duolingo. See <a href={streakSources.rule.url} target="_blank" rel="noreferrer">the original account</a> for context.</figcaption></figure></details>}</>}</div></section>)}
 <section className="case-sources" id="sources"><span className="eyebrow">Follow the evidence</span><h2>Sources, scope, and the next step.</h2><ul>{Object.values(streakSources).map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.label} ↗</a></li>)}</ul><p>Reported lifts belong to the experiments described by Duolingo. They do not establish that the same feature will produce the same effect elsewhere. The baseline calculator, fictional learner, decision exercise, and proposed guardrails are PMcademy teaching material.</p><div className="page-actions"><Link className="btn btn-primary" href="/levels/01/retention-is-the-number">Learn to read retention ↗</Link><Link className="btn btn-outline" href="/case-studies">Back to the observation room</Link></div></section>
 <ReadTracker id="duolingo-streak" title="Duolingo: a better streak" href="/case-studies/duolingo-streak"/>
 </article>;}
