"use client";
import Link from 'next/link';
import {useState} from 'react';
import {levels,levelLessons} from '@/lib/course';
import {activityForDay} from '@/lib/workspace/activity';
import {workspaceAction,toggleHidden,saveProject,savePublished,updateProfile} from '@/lib/workspace/store';
import type {PanelId} from '@/lib/workspace/scene';
import type {WorkspaceState,WorkspaceRecord,ProjectType} from '@/lib/workspace/types';
export const PANEL_TITLES:Record<PanelId,string>={mentor:'Your next chapter',cases:'The reading shelf',calendar:'Your learning calendar',projects:'Your product work',published:'Ideas you put into the world',badges:'Milestones in your practice',streak:'A growing practice',share:'Your room, your audience',notes:'Your private notebook',explore:'Explore the curriculum'};
const date=(iso:string)=>new Date(iso).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
const empty=(message:string)=><p className="ws-panel-empty">{message}</p>;
export function MentorPanel({state}:{state:WorkspaceState}) {
 const next=state.progress.nextLesson,last=state.activity.find(a=>a.type!=='badge_earned');
 const prompt=`I am learning product management at PMcademy. My next lesson is ${next?.title??'a portfolio review'}. My recent work: ${last?.label??'I am just starting'}. Act as a critical thinking partner. Ask one question at a time, help me identify evidence and assumptions, and critique my reasoning. Do not invent research or do the assignment for me.`;
 return <div className="ws-panel-stack"><span className="eyebrow">One useful next step</span><h3>{next?.title??'Make something worth sharing.'}</h3><p>{last?`Last time, you worked on ${last.label}.`:'Start with your first lesson. A paper will appear on your desk when you complete it.'}</p>{next&&<Link className="btn btn-primary" href={`/levels/${next.levelSlug}/${next.slug}`}>Continue learning · ~{next.minutes} min ↗</Link>}<label htmlFor="ws-ai">Take this context to your AI assistant</label><textarea id="ws-ai" readOnly value={prompt} rows={6} className="ws-input"/><p className="ws-small">Use Claude, Cursor or Codex alongside the lesson. Keep the evidence and final judgement yours.</p></div>;
}
export function CasesPanel({state}:{state:WorkspaceState}){return <div className="ws-panel-stack">{!state.caseStudies.length?empty('Read a case study and its book will find a home here.'):<ul className="ws-evidence-list">{state.caseStudies.map(c=><li key={c.caseStudyId}><Link href={c.href}><strong>{c.title}</strong><span>{c.completedAt&&date(c.completedAt)} ↗</span></Link></li>)}</ul>}<Link href="/case-studies" className="btn btn-outline">Find your next read ↗</Link></div>;}
export function CalendarPanel({state}:{state:WorkspaceState}) {
 const [selected,setSelected]=useState(state.streak.days.at(-1)?.day??'');
 const entries=activityForDay(state.activity,selected);
 return <div className="ws-panel-stack"><p><strong>{state.streak.current} days</strong> in your current streak · <strong>{state.streak.longest}</strong> personal best</p><p className="ws-small">The last 13 weeks. Select a date to revisit your work.</p><div className="ws-calendar-grid">{state.streak.days.map(d=><button key={d.day} title={d.day} className="ws-day" data-active={d.count>0} aria-label={`${d.day}: ${d.count} learning actions`} aria-pressed={selected===d.day} onClick={()=>setSelected(d.day)}>{d.day.slice(-2)}</button>)}</div><h3>{selected}</h3>{entries.length?<ul className="ws-evidence-list">{entries.map(a=><li key={a.id}><strong>{a.label}</strong><span>{a.type.replaceAll('_',' ')}</span></li>)}</ul>:empty('No learning activity recorded on this date.')}</div>;
}
export function BadgesPanel({state}:{state:WorkspaceState}) {return <div className="ws-panel-stack"><p className="ws-small">Study milestones recognise your practice. Reviewed capstone credentials are awarded separately.</p>{state.badges.length?<ul className="ws-milestones">{state.badges.map((b,i)=><li key={b.id} data-rarity={b.rarity}><svg viewBox="0 0 80 90" aria-hidden="true"><path d="M40 3 72 20v42L40 85 8 62V20Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d="m40 17 7 17 18 3-13 13 3 19-15-9-15 9 3-19-13-13 18-3Z" fill="currentColor" opacity=".65"/><text x="40" y="49" textAnchor="middle" fontSize="13" fill="var(--paper)">{i+1}</text></svg><h3>{b.title}</h3><p>{b.description}</p><span>{date(b.earnedAt)}</span></li>)}</ul>:empty('Your first milestone arrives with your first completed lesson.')}</div>;}
export function StreakPanel({state}:{state:WorkspaceState}) {return <div className="ws-panel-stack"><h3>{state.streak.current} days of showing up for the work.</h3><p>Your best run is {state.streak.longest} days. {state.streak.activeToday?'Today counts. Take a breath.':'Complete a lesson, read a case study, or submit a project to make today count.'}</p><p>The plant grows at 7, 14 and 30 days. Your earned milestones stay with you even when you take a break.</p><Link href="/levels" className="btn btn-primary">Find a lesson ↗</Link></div>;}
function Evidence({state,kind}:{state:WorkspaceState;kind:'projects'|'published'}) {return <ul className="ws-evidence-list">{kind==='projects'?state.projects.map(p=><li key={p.id}><Link href={`/u/${state.profile.username}/projects/${p.slug}`}><strong>{p.title}</strong><span>{p.type} · {p.status}</span></Link></li>):state.published.map(w=><li key={w.id}><a href={w.url} target="_blank" rel="noopener noreferrer"><strong>{w.title}</strong><span>{w.platform} ↗</span></a></li>)}</ul>;}
export function ProjectsPanel({state,busy=false}:{state:WorkspaceState;busy?:boolean}) {
 const [message,setMessage]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>) {e.preventDefault();const form=e.currentTarget,d=new FormData(form);const ok=await saveProject({title:String(d.get('title')),summary:String(d.get('summary')),url:String(d.get('url')),type:String(d.get('type')) as ProjectType,status:String(d.get('status')) as 'draft'|'submitted'});if(ok){form.reset();setMessage('Your project is on the desk.');}}
 return <div className="ws-panel-stack"><Evidence state={state} kind="projects"/>{!state.projects.length&&empty('Your first project folder belongs here.')}<form onSubmit={submit} className="ws-form"><label>Project title<input name="title" className="ws-input" required maxLength={160}/></label><label>Kind<select name="type" className="ws-input">{['teardown','research','prd','experiment','metrics','prototype','gtm','ai-concept','memo'].map(t=><option key={t}>{t}</option>)}</select></label><label>What did you investigate or build?<textarea name="summary" className="ws-input" rows={4} maxLength={4000}/></label><label>Project link<input name="url" type="url" className="ws-input" placeholder="https://"/></label><label>Status<select name="status" className="ws-input"><option value="draft">Still working on it</option><option value="submitted">Ready to share</option></select></label><button className="btn btn-primary" disabled={busy}>Save project</button><p role="status">{message}</p></form></div>;
}
export function PublishedPanel({state,busy=false}:{state:WorkspaceState;busy?:boolean}) {
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);if(await savePublished({title:String(d.get('title')),url:String(d.get('url'))}))form.reset();}
 return <div className="ws-panel-stack"><Evidence state={state} kind="published"/><p>Share what your project taught you on Medium, Substack, LinkedIn, Reddit or your own site. Add it here to pin it to your wall.</p><form onSubmit={submit} className="ws-form"><label>Article title<input name="title" required maxLength={160} className="ws-input"/></label><label>Article link<input name="url" type="url" required className="ws-input"/></label><button disabled={busy} className="btn btn-primary">Pin your writing</button></form></div>;
}
export function SharePanel({state,busy=false,record}:{state:WorkspaceState;busy?:boolean;record?:WorkspaceRecord}) {
 const [message,setMessage]=useState('');const url=typeof window==='undefined'?'':`${window.location.origin}/u/${state.profile.username}`;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);if(await updateProfile({displayName:String(d.get('name')),username:String(d.get('username')),bio:String(d.get('bio')),visibility:String(d.get('visibility')) as typeof state.profile.visibility}))setMessage('Your profile is saved.');}
 const items=[...state.projects.map(p=>({id:p.id,title:p.title})),...state.published.map(p=>({id:p.id,title:p.title})),...state.caseStudies.map(p=>({id:p.caseStudyId,title:p.title})),...state.badges.map(p=>({id:p.id,title:p.title}))];
 return <div className="ws-panel-stack"><form onSubmit={submit} className="ws-form"><label>Name<input name="name" defaultValue={state.profile.displayName} required maxLength={80} className="ws-input"/></label><label>Username<input name="username" defaultValue={state.profile.username} pattern="[a-z0-9][a-z0-9-]{2,39}" required className="ws-input"/></label><label>About your practice<textarea name="bio" defaultValue={state.profile.bio} maxLength={320} className="ws-input"/></label><label>Who can visit?<select name="visibility" defaultValue={state.profile.visibility} className="ws-input"><option value="private">Only me</option><option value="community">Signed-in PMcademy learners</option><option value="public">Everyone, including search engines</option></select></label><button disabled={busy} className="btn btn-primary">Save profile</button></form><label>Your permanent room address<input className="ws-input" value={url} readOnly onFocus={e=>e.currentTarget.select()}/></label><button className="btn btn-outline" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage('Room link copied.');}catch{setMessage('Select the address above to copy it.');}}}>Copy room link ↗</button><p className="ws-small">Visibility changes apply to this same address. Your private notebook and draft projects are never shared.</p><details><summary>Choose what visitors see</summary>{items.map(item=><label className="ws-visibility-row" key={item.id}><input type="checkbox" disabled={busy} checked={!state.profile.hidden.includes(item.id)} onChange={()=>void toggleHidden(item.id)}/>{item.title}</label>)}</details><details><summary>Invite someone to learn with you</summary><p className="ws-small">Share this code with a new learner. Your postcard arrives when they finish their first lesson.</p><input aria-label="Your invite code" readOnly value={record?.referralCode??''} className="ws-input" onFocus={e=>e.currentTarget.select()}/><p>{state.referrals.converted} learners started with your invitation.</p><form className="ws-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const code=String(new FormData(form).get('code'));if(await workspaceAction('referral',{code})){setMessage('Invitation saved. Complete your first lesson to make it count.');form.reset();}}}><label>Were you invited? Add your code before your first lesson.<input name="code" required maxLength={40} className="ws-input"/></label><button disabled={busy} className="btn btn-outline">Apply invite</button></form></details><p role="status">{message}</p></div>;
}
function Notes({record,busy}:{record:WorkspaceRecord;busy:boolean}){const [text,setText]=useState(record.notes??''),[saved,setSaved]=useState(false);return <div className="ws-panel-stack"><p>Questions, observations, loose ends. Only you can read this notebook.</p><textarea aria-label="Private notes" value={text} onChange={e=>{setText(e.target.value);setSaved(false);}} maxLength={20000} rows={14} className="ws-input"/><button disabled={busy} className="btn btn-primary" onClick={async()=>setSaved(await workspaceAction('notes',{text}))}>Save notes</button><p role="status">{saved?'Notebook saved.':''}</p></div>;}
export function WorkspacePanel({panel,state,record,busy}:{panel:PanelId|null;state:WorkspaceState;record:WorkspaceRecord;busy:boolean}) {
 switch(panel){case 'mentor':return <MentorPanel state={state}/>;case 'cases':return <CasesPanel state={state}/>;case 'calendar':return <CalendarPanel state={state}/>;case 'projects':return <ProjectsPanel state={state} busy={busy}/>;case 'published':return <PublishedPanel state={state} busy={busy}/>;case 'badges':return <BadgesPanel state={state}/>;case 'streak':return <StreakPanel state={state}/>;case 'share':return <SharePanel state={state} busy={busy} record={record}/>;case 'notes':return <Notes record={record} busy={busy}/>;case 'explore':return <ul className="ws-evidence-list">{levels.map(l=><li key={l.slug}><Link href={`/levels/${l.slug}`}><strong>{l.rank}</strong><span>{levelLessons(l).length} lessons · View level ↗</span></Link></li>)}</ul>;default:return null;}
}
