"use client";
import { useId, useState } from "react";
import Link from "next/link";
import JourneyScene from "./JourneyScene";
import MotionFrame from "./MotionFrame";
const steps=[
 {label:"Read the signal",title:"Three reviews. Two different problems.",body:"A learner cannot verify an account. Another gets logged out mid-session. A third asks for dark mode. Keep the original words before you group anything.",artifact:"Your evidence: one row per review, with a source ID."},
 {label:"Check the AI",title:"One tidy cluster can hide two causes.",body:"AI groups the first two reports under “login”. You inspect the quotes and separate verification from session stability. Similar words do not prove a shared cause.",artifact:"Your judgment: split the cluster and record why."},
 {label:"Make the call",title:"Choose a next step you can defend.",body:"You recommend checking verification failures first, name the missing data, and explain what would change your mind. You have a decision, not a feature wishlist.",artifact:"Your build: a one-page memo with evidence and a next action."},
];
export default function LessonJourney(){const [step,setStep]=useState(0);const id=useId();return <section className="section rule" id="inside-a-lesson"><div className="shell"><header className="head"><span className="eyebrow">Inside a lesson</span><h2>A messy inbox becomes a clear decision.</h2><p>Try a miniature version of your first Monday as a PM. Read the evidence, challenge an AI shortcut, and leave with a memo you can explain.</p></header><div className="lesson-journey"><MotionFrame label="lesson animation" className="journey-art"><svg viewBox="0 0 640 440" role="img" aria-labelledby={`${id}-title`}><title id={`${id}-title`}>{steps[step].title}</title><defs><linearGradient id={`${id}-sky`} x2="0" y2="1"><stop stopColor="var(--art-sky)"/><stop offset="1" stopColor="var(--art-water-deep)"/></linearGradient></defs><path d="M35 380V195C35-30 605-30 605 195v185Z" fill={`url(#${id}-sky)`} stroke="var(--art-rim)"/><circle cx="509" cy="108" r="43" fill="var(--art-sun)"/><path d="M35 354 113 278 206 345 282 299 398 355 523 274 605 342v38H35Z" fill="var(--art-mountain)"/><path d="M35 369q155-30 285 0t285 0v24H35Z" fill="var(--art-water)"/>
<JourneyScene key={step} step={step}/>
<g fill="var(--art-ochre)" className="journey-spark"><path d="m320 85 5 14 14 5-14 5-5 14-5-14-14-5 14-5Z"/><path d="m560 287 3 9 9 3-9 3-3 9-3-9-9-3 9-3Z"/></g><path d="M28 394h585m-564 8h540" stroke="var(--art-rim)"/><g fill="var(--art-sage)" stroke="var(--art-outline)"><path d="M57 393q-33-30-29-74 38 6 29 74q35-43 49-27-9 28-49 27M585 393q-25-38-10-64 25 9 10 64q27-37 37-16-8 22-37 16"/></g></svg><p className="journey-caption">Illustrative practice scenario · Source IDs stay with the evidence.</p></MotionFrame><div className="journey-content"><div className="journey-tabs" role="group" aria-label="Explore the lesson workflow">{steps.map((s,i)=><button key={s.label} type="button" aria-pressed={i===step} onClick={()=>setStep(i)}><span>0{i+1}</span>{s.label}</button>)}</div><div className="journey-explanation" key={step}><span className="eyebrow">Step {step+1} of 3</span><h3>{steps[step].title}</h3><p>{steps[step].body}</p><aside>{steps[step].artifact}</aside></div><Link className="btn btn-primary" href="/levels/start">Try the full lesson ↗</Link></div></div></div></section>;}
