import Link from 'next/link';
import {notFound} from 'next/navigation';
import {caseStories} from '@/lib/case-stories';
import CaseArtwork from '@/components/case-studies/CaseArtwork';
import CaseMechanism from '@/components/case-studies/CaseMechanism';
import {CaseBuild,CaseDecision} from '@/components/case-studies/CaseDecision';
import MotionFrame from '@/components/art/MotionFrame';
export function generateStaticParams(){return caseStories.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params,s=caseStories.find(x=>x.slug===slug);return{title:s?`${s.brand}: ${s.title}`:'Case study',description:s?.dek};}
export default async function CasePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params,story=caseStories.find(x=>x.slug===slug);if(!story)notFound();return <article className="visual-case section-top"><div className="shell"><Link href="/case-studies" className="case-back">← All case studies</Link><header className="case-hero"><div><span className="eyebrow">{story.brand} · {story.category}</span><h1>{story.title}</h1><p>{story.dek}</p><small>7 chapters · Interactive · Free</small></div><MotionFrame label={`${story.brand} cover`}><CaseArtwork kind={story.art} brand={story.brand}/></MotionFrame></header><aside className="case-source"><span className="eyebrow">The source · {story.period}</span><p>{story.fact}</p><a href={story.source.url} target="_blank" rel="noreferrer">{story.source.label} ↗</a></aside><p className="case-disclosure">Independent educational analysis. The scenarios, numbers and illustrations below are original PMcademy practice material, not company research results or an endorsement.</p><nav className="case-chapter-nav" aria-label="Case chapters">{story.chapters.map((c,i)=><a key={c.id} href={`#${c.id}`}><span>0{i+1}</span>{c.label}</a>)}</nav>{story.chapters.map((c,i)=><section className="case-story-section rule" key={c.id} id={c.id}><header><span className="eyebrow">0{i+1} · {c.label}</span><h2>{c.title}</h2></header><div className="case-section-body"><p>{c.body}</p>{c.id==='mechanism'&&<CaseMechanism story={story}/>} {c.id==='decision'&&<CaseDecision story={story}/>} {c.id==='apply'&&<CaseBuild story={story}/>}</div></section>)}<aside className="case-editorial-note"><p>Read the <a href={story.source.url} target="_blank" rel="noreferrer">original {story.brand} account</a> for the historical company explanation. Company names and marks belong to their respective owners and identify the subject of this independent case study.</p><Link href="/case-studies">Explore another story ↗</Link></aside></div></article>;}
